services:
  mqtt-server:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto:/mosquitto/config
    command: mosquitto -c /mosquitto/config/mosquitto.conf
    networks:
      - ip6net

  cs:
    build:
      context: ./charging-station
    depends_on:
      - mqtt-server
    environment:
      - MQTT_SERVER_ADDRESS=mqtt-server
      - SCRIPT_TO_RUN=run-sil.sh
      - FLOW_FILE=config-sil-flow.json
    volumes:
      - nodered_data:/everest/everest-workspace/everest-core/config/nodered
    networks:
      - ip6net

  nodered:
    image: ghcr.io/everest/everest-dev-environment/nodered:docker-images-v0.1.0
    depends_on:
      - mqtt-server
      - cs
    volumes:
      - nodered_data:/data
    networks:
      - ip6net
    ports:
      - "1880:1880"
    environment:
      - MQTT_SERVER_ADDRESS=mqtt-server

networks:
  ip6net:
    enable_ipv6: true
    ipam:
      driver: default

volumes:
  nodered_data: